"""Update violation model

Revision ID: 7c7c63156a56
Revises: 0
Create Date: 2025-04-12 14:58:00.692127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7c63156a56'
down_revision = '0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_type')
    op.drop_table('camera_check')
    with op.batch_alter_table('violation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('violation_source_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('violation_number', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('violation_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=False))
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('violation_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'club', ['club_id'], ['id'])
        batch_op.create_foreign_key(None, 'violation_source', ['violation_source_id'], ['id'])
        batch_op.drop_column('date')
        batch_op.drop_column('action_taken')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('reported_by')
        batch_op.drop_column('description')
        batch_op.drop_column('action_type_id')

    with op.batch_alter_table('violation_type', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.drop_column('severity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violation_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('severity', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('violation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_type_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('reported_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('action_taken', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'action_type', ['action_type_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['reported_by'], ['id'])
        batch_op.alter_column('violation_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('created_by')
        batch_op.drop_column('notes')
        batch_op.drop_column('violation_date')
        batch_op.drop_column('violation_number')
        batch_op.drop_column('violation_source_id')
        batch_op.drop_column('club_id')

    op.create_table('camera_check',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('club_id', sa.INTEGER(), nullable=True),
    sa.Column('check_time', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('checked_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['checked_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_type',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
